version: "3"
services:
  btsd-coid-adapter:
    image: "registry.supreme-team.tech/coid-adapter-backend"
    volumes:
      - /certs/rsa.p12:/certs/rsa.p12
      - /certs/1ec.pfx:/certs/1ec.pfx
    environment:
       COID_URL: https://online.kisc.kz:443/
      # nosec-prevline
       COID_RSA_CERTIFICATE: /certs/rsa.p12
       COID_RSA_CERTIFICATE_PASSWORD: YOUR_PASSWORD
       COID_GOST_CERTIFICATE_C_N: PCIDTEST.YOUR_CNN
       COID_GOST_CERTIFICATE: /certs/1ec.pfx
       COID_GOST_CERTIFICATE_PASSWORD: YOUR_PASSWORD
       ACCESS_LOGIN: YOUR_USER
       ACCESS_PASSWORD: YOUR_PASSWORD
      # nosec-prevline
       ACCESS_PERSONAL_DATA_PASSWORD: YOUR_PASSWORD
    ports:
      - "8080:8888"
